name: recipe-database-website

services:
  db: # the name of the service that will host the SQL database
    image: postgres:15-alpine
    container_name: recipe-postgres-container
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/ # create a location to save the SQL data when the container is down
    env_file:
      - "prod.env"
    networks:
      - recipe_network

  web: # The name of the service that will host the website
    build: .
    image: recipe-website
    container_name: recipe-website-container
    command: gunicorn --bind 0.0.0.0:8000 --workers=3 cookbook.wsgi:application
    volumes:
      - .:/app # sync the host directory to the working directory
      - recipe_static_volume:/app/staticfiles
    depends_on:
      - db
    env_file:
      - "prod.env"
    networks:
      - recipe_network

  frontend: # The name of the service that will act at the "frontend"
    image: nginx:alpine
    container_name: recipe-frontend-container
    ports:
      - "8001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - recipe_static_volume:/app/staticfiles:ro
    networks:
      - recipe_network
    depends_on:
      - web

volumes:
  postgres_data:
  recipe_static_volume:

# Create an isolated network for the containers that are part of this Docker Compose.
networks:
  recipe_network:
    driver: bridge