name: recipe-database-website

services:
  db:
    image: postgres:15-alpine
    container_name: recipe-postgres-container
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - "prod.env"
    networks:
      - recipe_network

  web:
    build: .
    container_name: recipe-website-container
    command: gunicorn --bind 0.0.0.0:8000 --workers=3 cookbook.wsgi:application
    volumes:
      - .:/app
      - recipe_static_volume:/app/staticfiles
    depends_on:
      - db
    env_file:
      - "prod.env"
    networks:
      - recipe_network
    restart: unless-stopped

  frontend:
    image: nginx:alpine
    container_name: recipe-frontend-container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - recipe_static_volume:/app/staticfiles:ro
    networks:
      - recipe_network
    depends_on:
      - web
    restart: unless-stopped

volumes:
  postgres_data:
  recipe_static_volume:

networks:
  recipe_network:
    driver: bridge